config/routes.rb
Rails.application.routes.draw do

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  get 'products/new'

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get '/help',            to: 'static_pages#help'
  get '/about',           to: 'static_pages#about'
  get '/contact',         to: 'static_pages#contact'
  get '/login',           to: 'sessions#new'
  post '/login',          to: 'sessions#create'
  delete '/logout',       to: 'sessions#destroy'
  get '/newlisting',      to: 'products#new'
  post '/newlisting',     to: 'products#create'
  resources :users
  resources :products
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
end
  

app/views/layouts/_bootstrap_spcart_partial.html.erb
<%= # Not needed, creates a double product order when clicking on product %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <% if request.ssl? %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% else %> 
    <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% end %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        <%= link_to "AmpliFire Energetics", root_path %>
    </small>
    <nav>
        <ul>
            <li><%= link_to "About",   about_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <% if logged_in? && current_user.admin? %>
                <li><%= link_to "Log out", logout_path, method: "delete" %>
            <% else %>
                <li><%= link_to "Admin? Click here", login_path %></li>
            <% end %>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "AmpliFire Energetics", root_path, id: "logo" %>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Products", products_path %></li>
                <% # For showing subtotal%>
                <li>
                    <%= render 'layouts/cart_text' %>
                </li>
                    <% if logged_in? && current_user.admin? %>
                        <%= render 'layouts/header_logged_in' %>
                    <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_header_logged_in.html.erb
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Account <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
        <li><%= link_to "Create listing", newlisting_path %></li>
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
    </ul>
</li>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 
                                'data-turbolinks-track': 'reload'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
      <%= render 'layouts/rails_default' %>
      <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <% #for anchoring the footer to the bottom of the page %>
      <div class="clearfooter"></div>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>